# Generated by Django 3.2.13 on 2024-05-22 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_part_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='slug',
            field=models.SlugField(blank=True, max_length=64, null=True),
        ),
    ]
