# Generated by Django 3.2.13 on 2024-05-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='parts',
            field=models.ManyToManyField(to='parts.Part'),
        ),
    ]
